### ISSUE TITLE
 <swui-datatable> is not working

### ISSUE THREAD

**Issue by anusreemn** [swimlane/angular2-data-table#336] opened 2016-12-02 14:11 UTC
Hi,

I imported the latest of this component. But the tag _swui-datatable_ is not working. It is throwing an entire length of errors. _datatable_ does alone work. Please resolve.

**Comment by amcdnl** [comment] 2016-12-02 14:14
1) Please fill out the form in the github.
2) Please use manners when filling out tickets, phrases like 'Please resolve' is not appropriate.
3) Statements like 'is not working' is not a way to report a bug. Please give detailed errors and reproduction cases.
4) The demos seems to be working and others have reported it working so its likely something related to your implementation. Review the changelog and demo code.

I'm closing until 3 and 4 are provided.

**Closed by amcdnl** 2016-12-02 14:14 UTC
Labels: Need More Info
