### ISSUE TITLE
TableOptions are being overwritten with multiple tables on the screen.

### ISSUE THREAD

**Issue by jvanhall** [swimlane/angular2-data-table#91] opened 2016-08-30 20:11 UTC
We are seeing an issue where the options are overwritten and all the tables on the screen end up with the same options, including columns.

[https://plnkr.co/edit/AKy4ZtuLmpmrMk83F2sW](url)

**Comment by jvanhall** [comment] 2016-09-07 13:55
Any update on this?  It's preventing us from using the module and we would really like to use it.  Thanks!

**Comment by amcdnl** [comment] 2016-09-07 15:43
Duplicate of #103, work in progress.

**Closed by amcdnl** 2016-09-07 15:43 UTC
Labels: Bug, Investigate
