### ISSUE TITLE
Row groupping

### ISSUE THREAD

**Issue by ipassynk** [swimlane/angular2-data-table#312] opened 2016-11-23 19:53 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here
```

**Expected behavior**
I want to be able to group rows  and be able to expand/collapse groups. Something like: https://www.ag-grid.com/javascript-grid-grouping/

**Reproduction of the problem**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Table version:** 0.7.x

* **Angular version:** 2.0.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by amcdnl** [comment] 2016-11-23 22:24
Duplicate of #35. Please review existing issues before submitting new ones.

**Closed by amcdnl** 2016-11-23 22:24 UTC
