### ISSUE TITLE
Got an error: 'Import or export declaration in an ambient module declaration cannot reference module through relative module name'

### ISSUE THREAD

**Issue by dream83619** [swimlane/angular2-data-table#56] opened 2016-08-15 06:33 UTC
Got an error when compiling:

> ERROR in [default] c:\Codes\angular2\quick-start\node_modules\angular2-data-table\release\angular2-data-table.d.ts:176:4              
> Import or export declaration in an ambient module declaration cannot reference module through relative module name.

How to fix such a kind of error? Thanks.

**Comment by amcdnl** [comment] 2016-08-15 12:40
The file is there, see: https://github.com/swimlane/angular2-data-table/blob/master/release/angular2-data-table.d.ts

Can you provide a demo maybe?

**Comment by amcdnl** [comment] 2016-08-18 12:06
Dupe of #55

**Closed by amcdnl** 2016-08-18 12:06 UTC
Labels: Duplicate
