### ISSUE TITLE
Sorting does not work in template header

### ISSUE THREAD

**Issue by Medesko** [swimlane/angular2-data-table#362] opened 2016-12-12 10:16 UTC
Hi Thank for this amazing job, 

the sort does not work  in template header, 

any idea for help!

**Comment by Thoma5** [comment] 2016-12-12 10:38
I think this is a duplicate of #233. 
If you just want to change the name of a column, you can do this by using the name and prop attribute like: `name="#" prop="number"` where prop is the name of the member in your object and # will be viewed as the column name.

**Closed** 2016-12-12 14:10 UTC
