### ISSUE TITLE
angular2-data-table.d.ts' is not a module. Please contact the package author to update the package definition

### ISSUE THREAD

**Issue by katsuki-nakatani** [swimlane/angular2-data-table#55] opened 2016-08-15 06:21 UTC
release/angular2-data-table.d.ts 

line 483
add prefix keyword export is compile success 

`
export declare module "angular2-data-table"
`

my environment is angular-cli

**Comment by amcdnl** [comment] 2016-08-15 12:43
Try now please. This file is generated by the build, need to figure out how to do this automagic for now i manually added

**Comment by adaur** [comment] 2016-08-15 17:11
I had the same problem, your commit fixed it. Thanks.

**Comment by amcdnl** [comment] 2016-08-15 17:17
Typescript is sooo annoying sometimes! Let me do some research on how to package this, this is a big issue everyone is having.

**Comment by adaur** [comment] 2016-08-15 17:23
The problem seems to be with the reference to core-js at the very first line. I've tried to use this file without luck.

https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/core-js/core-js.d.ts

**Comment by katsuki-nakatani** [comment] 2016-08-16 00:02
@amcdnl 
0.2.3 is non problem
Thanks!

**Comment by amcdnl** [comment] 2016-08-16 01:31
Was wondering if one of you could do me a favor and try this out - https://github.com/swimlane/angular2-data-table/tree/better-build

**Comment by adaur** [comment] 2016-08-16 19:23
There are less errors:

`ERROR in ./app/home.component.ts
 (5,41): error TS2307: Cannot find module 'angular2-data-table'.

 ERROR in ./app/home.component.ts
 (11,8): error TS2307: Cannot find module 'angular2-data-table'.

 ERROR in ./app/app.module.ts
 (16,41): error TS2307: Cannot find module 'angular2-data-table'.

 ERROR in ./app/app.module.ts
 (21,8): error TS2307: Cannot find module 'angular2-data-table'.`

**Comment by amcdnl** [comment] 2016-08-16 19:25
This is now on master.

**Comment by adaur** [comment] 2016-08-16 19:25
It seems good :)

**Comment by amcdnl** [comment] 2016-08-16 19:25
Finally! LOL

**Comment by adaur** [comment] 2016-08-16 19:33
I may have been too fast, sorry ^^

When I do

`import { Angular2DataTableModule } from 'angular2-data-table';

import {
	TableOptions,
	TableColumn,
	ColumnMode
} from 'angular2-data-table';`

I have a ts2307 error: cannot find module angular2-data-table.

However, the table is working well.

**Comment by amcdnl** [comment] 2016-08-16 19:48
Ugh... ok thanks

**Comment by Tempus35** [comment] 2016-08-17 23:38
I found when I did an import for it with 0.2.2 at least the import had to be:
`import {Angular2DataTableModule} from "angular2-data-table/release/angular2-data-table";`

**Comment by amcdnl** [comment] 2016-08-18 12:09
@DanielRosenwasser Is that the best way? Wouldn't declaring the typings fix this?

**Comment by DanielRosenwasser** [comment] 2016-08-18 16:59
How exactly do you want users to import your library?

**Comment by amcdnl** [comment] 2016-08-18 17:46
@DanielRosenwasser Like in this format - https://plnkr.co/edit/TLx2vYlCTLsqcLwvWafd?p=preview

**Comment by DanielRosenwasser** [comment] 2016-08-18 19:53
@Tempus35 can you try again today? Might very well be that it was fixed by #67.

**Comment by adaur** [comment] 2016-08-18 20:26
The error changed:

ERROR in ...\node_modules\angular2-data-table\release\models\TableOptions.d.ts
(1,1): error TS1084: Invalid 'reference' directive syntax.

**Comment by vijayanandkannan** [comment] 2016-08-18 20:41
I am defining angular2-data-table  in system.config.js as 'angular2-data-table': 'node_modules/angular2-data-table' and implementing it in as import {Angular2DataTableModule} from 'angular2-data-table'

I am getting error 'cannot find module 'angular2-data-table'

We converted our application to RC5.

Please let me know what I need to do?

-Vijay

**Comment by adaur** [comment] 2016-08-18 20:45
Please apply the following PRs and let us know if you are still experiencing the issue.

https://github.com/swimlane/angular2-data-table/pull/67
https://github.com/swimlane/angular2-data-table/pull/69

**Comment by vijayanandkannan** [comment] 2016-08-18 21:03
I changed the types to typings , but when I remove /// <reference types="core-js" /> from TableOptions.d.ts and made a build it is getting appended in the First line and give the same eror 

Error		Build:Invalid 'reference' directive syntax  in node_modules\angular2-data-table\release\models\TableOptions.d.ts	1

**Comment by fedotxxl** [comment] 2016-08-19 08:06
I imported angular2-data-table with webpack by `import {Angular2DataTableModule} from 'angular2-data-table/release/angular2-data-table';` and got an exception:

```
ERROR in /home/fbelov/job/projects-gramant/modeus/modeus-course-catalog/node_modules/angular2-data-table/release/models/TableOptions.d.ts
(1,1): error TS1084: Invalid 'reference' directive syntax.

ERROR in ./~/angular2-data-table/release/components/DataTable.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./datatable.scss in /home/fbelov/job/projects-gramant/modeus/modeus-course-catalog/node_modules/angular2-data-table/release/components
 @ ./~/angular2-data-table/release/components/DataTable.js 18:0-27
```

Is there any workaround?

**Comment by vijayanandkannan** [comment] 2016-08-19 14:06
For us to continue working if you give the files needed as single directory with package.json .... We can continue to work until the issue is researched and fixed.

**Comment by ocombe** [comment] 2016-08-22 08:40
Got the same problem :(
```
import {Angular2DataTableModule} from "angular2-data-table";
```

leads to the error `zone.js:484 Unhandled Promise rejection: Template parse errors:
Can't bind to 'rows' since it isn't a known property of 'datatable'.`

and 
```
import {Angular2DataTableModule} from "angular2-data-table/release/angular2-data-table";
```

leads to the error `client:47./~/angular2-data-table/release/components/DataTable.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./datatable.scss in C:\www\front-portal-v2\node_modules\angular2-data-table\release\components`

I'm using typescript 2.0.0 and webpack 1.13.2

**Comment by ocombe** [comment] 2016-08-22 08:56
Ok so the problem is just that you reference your scss in the source files, you should either use the `styles` property of the components and use an appropriate loader to transform your scss to css, or not import the scss files in your ts source files, and build the styles separately

**Comment by ocombe** [comment] 2016-08-22 09:17
Ok I went back to the original `import {Angular2DataTableModule} from "angular2-data-table";` which worked fine except for the "Template parse error".

I originally import the module into a submodule where my table is, but it didn't work.
I changed my code to import it into a shared module that is imported in all my other modules, and I added it to the `exports` property here, and now it works.

I tried to import/export it into my root NgModule but it doesn't work, only the shared module works :-/

**Comment by amcdnl** [comment] 2016-08-22 12:18
@ocombe:

> Ok so the problem is just that you reference your scss in the source file

The `release/angular2-data-table.js` is only for TypeScript defs. The main file uses the umd version and I recommend you use that. In that version the scss, is built straight into the source using rollup.

The bind error is related to the table not init'ing given the error.

**Comment by GoNode5** [comment] 2016-08-22 12:27
simple install... hour later:

I am defining angular2-data-table in system.config.js as 'angular2-data-table': 'node_modules/angular2-data-table' and implementing it in as import {Angular2DataTableModule} from 'angular2-data-table'
Leads to:
ERROR in ...\node_modules\angular2-data-table\release\models\TableOptions.d.ts
(1,1): error TS1084: Invalid 'reference' directive syntax.
Removing the
///
leads to 
http://localhost:3000/node_modules/angular2-data-table/release/components/datatable.scss.js 404 (Not Found)

and now...?

**Comment by ben-go** [comment] 2016-08-22 14:54
I don't know if that will help some of you but we never know..

To fix this error: 
```
ERROR in ...\node_modules\angular2-data-table\release\models\TableOptions.d.ts
(1,1): error TS1084: Invalid 'reference' directive syntax.
```
I have updated typescript to 2.0.0 - previously in 1.8.0

To fix this error: 
`Template parse errors: Can't bind to 'rows' since it isn't a known property`
I have updated angular to rc5 - previously in rc4

It also raised another error about types core-js not find so I installed @types/core-js via npm

Since I did many trials I wouldn't guaranty the execution order.
Hopefully that helps.

**Comment by vijayanandkannan** [comment] 2016-08-22 16:56
In the sytem.config.js I Implement 'angular2-data-table': 'node_modules/angular2-data-table' and in the shared module I import it as import {Angular2DataTableModule} from "angular2-data-table";  I am getting Build : Invalid 'reference' directive syntax and it is pointing to /// <reference types="core-js" /> in Tableoption.d.ts.

I am not sure what I need to do have it working. If someone can give me some detail work around that will help. I tried to implement what @GoNode5  mentioned but could not do so. I am not sure where I need to implement it. I also looked into the package.json to see if the version are different and it is rc5 and typescript 2.0.0

It will be helpful if someone can post the code so I can try it out.

**Comment by PiXeL16** [comment] 2016-08-23 18:23
Also stuck on this issue, got ```angular2-data-table/release/models/TableOptions.d.ts(1,1): error TS1084: Invalid 'reference' directive syntax.```

**Comment by alaingmail** [comment] 2016-08-23 22:50
I have the same issue with the error: `node_modules\angular2-data-table\release\models\TableOptions.d.ts (1,1): error TS1084: Invalid 'reference' directive syntax.`

**Comment by amcdnl** [comment] 2016-08-24 13:39
Can you guys try again in latest release 0.3.0 ?

**Comment by vijayanandkannan** [comment] 2016-08-24 14:09
No still Invalid reference directive syntax.

I added 'angular2-data-table': 'node_modules/angular2-data-table' in system. config and Imported in shared module (import {Angular2DataTableModule } from "angular2-data-table";).

When I build I am getting the Invalid reference directive syntax error.

**Comment by amcdnl** [comment] 2016-08-24 14:11
Try the UMD build one.

**Comment by vijayanandkannan** [comment] 2016-08-24 14:14
Can you help me how to define?

Is this how to define?

 'angular2-data-table': 'node_modules/angular2-data-table/release/angular2-data-table.umd.js' 
import {Angular2DataTableModule } from "angular2-data-table

**Comment by hwupu** [comment] 2016-08-24 16:32
As @ben-go mentioned, I was able to resolve `error TS1084: Invalid 'reference' directive syntax.` by switching to Typescript 2

As my understanding, typescript 2 is still under beta, so for the one who are willing to take risks, here are my steps:
1. `npm install --save-dev typescript@beta`
2. `npm install --save-dev @types/core-js @types/jasmine @types/node`
3. `rm -r typings*` **Caution!: I did this to remove old definitions that are no longer needed.**
4. remove `"postinstall": "typings install"` in `packages.json` as it is no longer needed also.
5. add those to `tsconfig.json`:
```
"compilerOptions": {
    ...
    "types": [
        "core-js",
        "jasmine",
        "node"
    ]
}
```

**Comment by amcdnl** [comment] 2016-08-24 16:40
U shouldn't need this anymore, can u try w/ latest?

**Comment by hwupu** [comment] 2016-08-24 16:47
@amcdnl I had just updated to 0.3.3 (previous post was like 0.2.5). Building was fine, but I still got ```
Error: Uncaught (in promise): Template parse errors:
Can't bind to 'row' since it isn't a known property of 'datatable-body-row'.
```

Also, you had mentioned UMD build, but I don't know how to set it up in webpack. any hints? Thx

**Comment by hwupu** [comment] 2016-08-25 04:32
One more update, I found out that the
```
Error: Uncaught (in promise): Template parse errors:
Can't bind to 'row' since it isn't a known property of 'datatable-body-row'.
```
issue was introduced by rc5, as stated under this: https://github.com/angular/angular/issues/10618

So, the temporary workaround is to add
```
plugins: [
    ...
    new webpack.optimize.UglifyJsPlugin({ mangle: { screw_ie8 : true, keep_fnames: true } })
]
```
to `webpack.prod.config`

**Comment by amcdnl** [comment] 2016-08-25 12:15
So I think we are good now :)

**Closed by amcdnl** 2016-08-25 12:15 UTC
Labels: Bug, Investigate

**Comment by TakhirMirzaev** [comment] 2016-10-13 17:20
C:\Projects\MGM\mandatory-webapp\node_modules\angular2-data-table\release\components\body\body-cell.component.d.ts
Error:(9, 5) TS2300: Duplicate identifier 'readonly'.

**Comment by TakhirMirzaev** [comment] 2016-10-13 17:21
I have lot errors from angular2-data-table

**Comment by amcdnl** [comment] 2016-10-17 13:43
@TakhirMirzaev can you paste the errors?

**Comment by TakhirMamirov** [comment] 2016-11-25 15:32
I'm getting bunch (around 80) of such errors:
Build: '=' expected.	\node_modules\angular2-data-table\release\components\body\body-cell.component.d.ts	9	
I've grabbed the latest angular2-data-table sources. No clue why that's happening...

**Comment by amcdnl** [comment] 2016-11-27 14:28
What node version...we only support >=6
